### ISSUE TITLE
could you give a example how to input the hessian in self define obj function

### ISSUE THREAD

**Issue by dbdxnuliba** [cshelton/pyminfunc#2]
could you give a example how to input the hessian in self define obj function, the three examples you give in python  don't give hessian 
![image](https://user-images.githubusercontent.com/13350158/231918495-b62e80d8-e67b-4e9a-a2c2-b2bc35439ebb.png)

**Comment by cshelton** [comment]
The Hessian would be defined as follows

```# silly function
def myf(x):
     sinx1 = np.sin(x[1])
     cosx1 = np.cos(x[1])
     f = x[0]**2 * sinx1**2 + (x[1]-10)**2 + (x[0]-10)**2
     g = np.array([2*x[0] * sinx1**2 + 2*(x[0]-10),
                   2*x[0]**2 * sinx1 * cosx1 + 2*(x[1]-10)])
     H = np.array([2 * sinx1**2 + 2  , 4*x[0]*sinx1*cosx1,
                   4*x[0]*sinx1*cosx1, 2*x[0]**2*(sinx1**2 - cosx2**2) + 2])
     return f,g,H
```
Note, I think there is a mistake in the gradient formula in the example python scripts.  I believe I fixed it here.
